export const worldConstants = {
  HEADER_OFFSET: 5 * 16, //5* 1rem lol
  WORLD_CANVAS_WIDTH: 800,
  LINE_WIDTH: 600,
  ITEM_GEN_TIMESPAN: 5000,
  IMG_SCALE_QUOTIENT: 1,
  BIN_IMG_SCALE: 0.43,
  ITEM_VELOCITY: 2,
  GRAB_DISTANCE: 1,
  THROWING_DISTANCE: 1,
  ITEM_WIDTH: 20,
  MANIP_RADIUS: 25,
  BIN_SIZE: {
    WIDTH: 50,
    HEIGHT: 100,
  },
};
